export const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #121013 0%, #2b1738 100%)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontFamily: 'system-ui, "Segoe UI", Roboto, sans-serif',
    padding: '2rem',
  },
  headerTitle: {
    fontSize: '3.5rem',
    fontWeight: '800',
    background: 'linear-gradient(to right, #c084fc, #f472b6)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '3rem',
    textAlign: 'center' as const,
    letterSpacing: '-0.02em',
  },
  card: {
    background: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '24px',
    padding: '2.5rem',
    width: '100%',
    maxWidth: '650px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  sectionTitle: {
    fontSize: '1.75rem',
    fontWeight: '600',
    marginBottom: '2rem',
    color: '#f3f4f6',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    paddingBottom: '1rem',
  },
  list: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  listItem: {
    background: 'rgba(255, 255, 255, 0.04)',
    borderRadius: '12px',
    padding: '1.25rem 1.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: '1px solid rgba(255, 255, 255, 0.05)',
  },
  productName: {
    fontWeight: '500',
    fontSize: '1.15rem',
    color: '#e5e7eb',
  },
  productPrice: {
    fontWeight: '700',
    fontSize: '1.25rem',
    color: '#c084fc',
    background: 'rgba(192, 132, 252, 0.1)',
    padding: '0.4rem 0.8rem',
    borderRadius: '8px',
  },
  errorText: {
    color: '#fca5a5',
    background: 'rgba(239, 68, 68, 0.15)',
    padding: '1rem',
    borderRadius: '8px',
    textAlign: 'center' as const,
    border: '1px solid rgba(239, 68, 68, 0.3)',
  },
  emptyText: {
    color: '#9ca3af',
    textAlign: 'center' as const,
    fontStyle: 'italic',
    padding: '2rem 0',
  }
};
